apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd-swarmrun.yaml
  - operator-rbac.yaml
  - swarm-runner-rbac.yaml
  - operator-configmap.yaml
  - operator-deployment.yaml
